name: Build GKI kernel
on:
  workflow_dispatch:

jobs:
  build-debug-kernel-a15:
    strategy:
      matrix:
        include:
          - version: "6.6"
            sub_level: 30
            os_patch_level: 2024-08
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android15-${{ matrix.version }}
      version_name: android15-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android15-${{ matrix.version }}-${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
      debug: false
